export const items=[
    {
        id: 1,
        category: 'laptop',
        title: "Lenovo IdeaPad Slim 7",
        imgSrc: "https://p1-ofp.static.pub//fes/cms/2024/07/18/wzhovltug9sbsfee95ldvntsomqehz568225.jpg",
        amazonLink: "",
        descriptions: "Acer Nitro 5 (15.6 inch, 16GB, 512GB SSD, AMD Ryzen 5 5600H, GeForce GTX 1650Ti, Windows 10 Home) Black",
        price: "39000",
    },{
        id: 2,
        category: 'mobile',
        title: "Apple iPhone 15",
        imgSrc: "https://m.media-amazon.com/images/I/71d7rfSl0wL._SX679_.jpg",
        amazonLink: "",
        descriptions: "Apple iPhone 15 (Blue, 128 GB)",
        price: "43000",
    },{
        id: 3,
        category: 'mobile',
        title: "Apple iPhone 16",
        imgSrc: "https://m.media-amazon.com/images/I/31TEA0qrUBL._SY445_SX342_QL70_FMwebp_.jpg",
        amazonLink: "",
        descriptions: "Apple iPhone 16",
        price: "80000",
    },{
        id: 4,
        category: 'mobile',
        title: "Apple iPhone 16 pro",
        imgSrc: "https://m.media-amazon.com/images/I/31TEA0qrUBL._SY445_SX342_QL70_FMwebp_.jpg",
        amazonLink: "",
        descriptions: "Apple iPhone 16pro",
        price: "180000",
    },{
        id: 5,
        category: 'laptop',
        title: "Asus VivoBook F15",
        imgSrc: "https://m.media-amazon.com/images/I/41QIrwK3LVL._SX300_SY300_QL70_FMwebp_.jpg",
        amazonLink: "",
        descriptions: "Asus VivoBook F15 (15.6 inch, 16GB, 512GB SSD, NVIDIA GeForce RTX 3060, Intel Core i7-11700K, Windows 10 Home) Black",
        price: "63000",
    },
    {
        id: 6,
        category: 'laptop',
        title: "Acer Nitro 5",
        imgSrc: "https://m.media-amazon.com/images/I/4144VzbbZ6L._SX300_SY300_QL70_FMwebp_.jpg",
        amazonLink: "",
        descriptions: "Acer Nitro 5 (15.6 inch, 16GB, 512GB SSD, AMD Ryzen 5 5600H, GeForce GTX 1650Ti, Windows 10 Home) Black",
        price: "49999",
    },{
        id: 7,
        category: 'clothes',
        title: "Polo T-Shirt for Men ",
        imgSrc: "https://m.media-amazon.com/images/I/61XTrRjs0mL._SX679_.jpg",
        amazonLink: "",
        descriptions: "AMERICAN CREW CottonPoly Solid Polo T-Shirt with No.3 Applique for Men (AC284)",
        price: "999",
    },{
        id: 8,
        category: 'mobile',
        title: "Samsung Galaxy M35 5G ",
        imgSrc: "https://m.media-amazon.com/images/I/51kH6DymEAL._SX300_SY300_QL70_FMwebp_.jpg",
        amazonLink: "",
        descriptions: "Samsung Galaxy M35 5G (Moonlight Blue,6GB RAM,128GB Storage)| Corning Gorilla Glass Victus+| AnTuTu Score 595K+ | Vapour Cooling Chamber | 6000mAh Battery | 120Hz Super AMOLED Display| Without Charger",
        price: "15000",
    },{
        id: 9,
        category: 'Shirt',
        title: "Samsung Galaxy S24 Ultra 5G ",
        imgSrc: "https://m.media-amazon.com/images/I/41QTM+veBgL._SY300_SX300_.jpg",
        amazonLink: "",
        descriptions: "Samsung Galaxy S24 Ultra 5G AI Smartphone (Titanium Yellow, 12GB, 256GB Storage)",
        price: "90000",
    },{
        id: 10,
        category: 'clothes',
        title: "Campus Men Shoes",
        imgSrc: "https://m.media-amazon.com/images/I/61IsvHMdgEL._SX625_.jpg",
        amazonLink: "",
        descriptions: "Campus Men's VACUM Running Shoes",
        price: "16300",
    },{
        id: 11,
        category: 'mobile',
        title: "Motorola Edge 50 Pro 5G ",
        imgSrc: "https://m.media-amazon.com/images/I/715aoVxQNTL._SX679_.jpg",
        amazonLink: "",
        descriptions: "Motorola Edge 50 Pro 5G with 125W Charger (Luxe Lavender, 256 GB) (12 GB RAM)",
        price: "36300",
    },
    {
        id: 12,
        category: 'mobile',
        title: "Redmi Note 13 Pro+",
        imgSrc: "https://m.media-amazon.com/images/I/31k+gXNf-hL._SY300_SX300_.jpg",
        amazonLink: "",
        descriptions: "Redmi Note 13 Pro+ (Fusion Purple, 8GB RAM, 256GB Storage) | World's First Mediatek 7200 Ultra 5G | 200MP Hi-Res Camera | 1.5K Curved AMOLED | 120W HyperCharge",
        price: "27599",
    },

    

]